# Generated by Django 2.1 on 2019-02-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('n_estimators', models.IntegerField()),
                ('criterion', models.CharField(max_length=50)),
                ('max_depth', models.IntegerField(max_length=50)),
            ],
        ),
    ]
