# Generated by Django 2.1 on 2019-02-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RFModel',
        ),
    ]
