# Generated by Django 2.1 on 2019-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfmodel',
            name='clf',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='rfmodel',
            name='max_depth',
            field=models.IntegerField(),
        ),
    ]
