# Generated by Django 2.1 on 2019-02-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190205_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfmodel',
            old_name='clf',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='rfmodel',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='rfmodel',
            name='max_depth',
        ),
        migrations.RemoveField(
            model_name='rfmodel',
            name='n_estimators',
        ),
    ]
